[package]
name = "render"
version = "0.1.0"
edition = "2021"


[dependencies]
winit = "0.27"
env_logger = "0.9"
log = "0.4"
wgpu = "0.13"
pollster = "0.2"
image = "0.24"
bytemuck = { version = "1.4", features = [ "derive" ]}
anyhow = "1.0"
glam = { version = "0.21.3", features = [ "bytemuck" ] }